### ISSUE TITLE
Everry time I log in I am taken to the registrars list

### ISSUE THREAD

**Issue by andydotxyz** [AletheiaWareLLC/spacefynego#6]
I don't know if this is a feature, but once I have signed up to some storage registrar I would expect to see just the files when I start the app.

<img width="912" alt="Screenshot 2021-04-07 at 18 22 29" src="https://user-images.githubusercontent.com/294436/113908317-4dd82480-97ce-11eb-86bd-6e70a8bb03e8.png">

**Comment by stuartmscott** [comment]
The user is shown the registrar list upon login if the number of providers they have setup is less than the recommendation (3) to ensure the user's data is as safe as possible. But you are right that it should be less "naggy", perhaps it should only be shown every X logins, or Y days, or maybe it should have a "don't remind me again" checkbox.

**Comment by andydotxyz** [comment]
Don't remind me again would work.
Though it would also need some sort of content showing "You have fewer than the recommended registrations" so people know why they are seeing it.
